apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: vote-app
spec:
  applicationOwner: erydrn
  securityLevel: internal
  stages:
    - name: azure-vote-back
      cluster:
        repository: https://github.com/erydrn/AKSwithFlux.git
        name: AKSwithFlux
      resources:
        path: cluster/namespaces/azure-vote-back
      previousStage: azure-vote-back
    - name: azure-vote-front
      cluster:
        repository: https://github.com/erydrn/AKSwithFlux.git
        name: AKSwithFlux
      resources:
        path: cluster/namespaces/azure-vote-front
      previousStage: azure-vote-front